### ISSUE TITLE
Ability to document blocks of code

### ISSUE THREAD

**Issue by carlosvega** [mozilla/sphinx-js#108]
It could be food if for example we want to document blocks such as:

```
/**
* ... 
*/
Vue.component({ ... 
 ... 
})
```

**Comment by carlosvega** [comment]
Anything?

**Comment by erikrose** [comment]
Could you be more specific as to what you mean?

**Comment by carlosvega** [comment]
For example, if there is a part of code in which I make a call to select2 or create a Vue component, I would love to add documentation to that part of the code. For instance, if you go to point 5 here, 
http://sethherr.github.io/soulheart/examples_select2/

documenting that select2 initialization could be very interesting. Same for Vue components. Thanks !

**Comment by erikrose** [comment]
I'm not aware of JSDoc supporting the extraction of generic comments from inside a function. Are you? Unfortunately, sphinx-js has only the output of JSDoc to work with.

**Comment by erikrose** [comment]
One idea: you could name your `function(data, page) {` function and put a proper doclet above it; that would give you a handle to extract some documentation by.

**Comment by carlosvega** [comment]
And then I can call it, yes. Like a closure. Good idea. Thanks!

**Comment by erikrose** [comment]
No problem! :-D
