### ISSUE TITLE
TypeScript overloads fail

### ISSUE THREAD

**Issue by tavianator** [mozilla/sphinx-js#110]
The following example:

```
function foo(bar: number): number;
function foo(bar: string): string;

function foo(bar: number | string): number | string {
    return bar;
}
```

Generates this error:

```
Exception occurred:
  File ".../site-packages/sphinx_js/doclets.py", line 49, in gather_doclets
    raise PathsTaken(conflicts)
sphinx_js.doclets.PathsTaken: Your JS code contains multiple documented objects at each of these paths:

  ./docs/foo.external:foo.foo

We won't know which one you're talking about. Using JSDoc tags like @class might help you differentiate them.
```

**Comment by erikrose** [comment]
[In the IR branch](https://github.com/erikrose/sphinx-js/blob/ir/sphinx_js/typedoc.py), I am arbitrarily just taking the first signature now. That ought to get it not crashing. Later, we can figure out how to show all the signature or choose among them or whatever.

**Comment by erikrose** [comment]
It doesn't fail anymore, but the ticket about showing all of them is #152. Cheers!
