### ISSUE TITLE
JSDoc contains the html tag like <p>, <em> etc (ex - docs./*** @classdesc NoSQLClient is <p>provides, <em>opt</em>  ). When I used  sphinx-js, end up with HTML tags in the output files. 

### ISSUE THREAD

**Issue by balicse01** [mozilla/sphinx-js#113]
**How I can avoid these html tags from the output** 

conf.json
 {                                                                               
      "source": {                                                                 
          "include": [                                                            
              "lib/nosql_client.js",                                              
              "lib/stmt.js",                                                      
              "lib/constants.js",                                                 
              "lib/error.js",                                                     
              "lib/utils.js",                                                     
              "lib/types/config.js",                                              
              "lib/types/param.js",                                               
              "lib/types/result.js",                                              
              "lib/types/data.js",                                                
              "lib/auth/config.js",                                               
              "lib/auth/idcs/types.js",                                           
              "lib/auth/idcs/file_credentials.js",                                
              "lib/auth/idcs/auth_provider.js"                                    
          ]                                                                       
      },                                                                          
      "opts": {                                                                   
          "encoding": "utf8",                                                     
          "destination": "./doc/api/",                                            
          "template": "node_modules/docdash",                                     
          "readme": "./doc/index.md",                                             
          "tutorials": "./doc/guides"                                             
      },                                                                          
      "docdash": {                                                                
          "typedefs": true,                                                       
          "search": true,                                                         
          "wrap": true,                                                           
          "collapse": true                                                        
      }                                                                           
  }

**Comment by erikrose** [comment]
I don't understand what that pasted JSON is. If it's important, please do explain.

Apart from that, sphinx-js supports reStructuredText, for consistency with Sphinx. It does not support free HTML in doclets, which is a peculiarity of Markdown. It probably never will, as that would prevent Sphinx from rendering our output to non-HTML formats like PDF or Latex. I recommend using the reST equivalents of tags like `<b>` and `<em>` if you want to use sphinx-js.
