### ISSUE TITLE
Typescript interface renders as 'class'

### ISSUE THREAD

**Issue by mdolgich** [mozilla/sphinx-js#118]
Hey guys, 
yesterday I started using your generation tool for a project. Sadly I have found a few problems when trying to apply it to our TypeScript project. I have formulated some fixes for the direct problems I had and will post a PR about those.
One problem I cannot ascertain is why my interfaces get rendered as `class` even though it states one line further that it was marked as an interface.

Kind regards 
Maxim

Please see the screenshot for reference. The corresponding code is:
```typescript
/**
 * A super cool interface.
 */
export interface SuperCoolInterface {
    init (
        higherOrderFunction:(request: number) => Promise<Promise<number[]>>): Promise<void>;

    /**
     * super important function
     * @param response totally legit number parameter
     */
    importantFunction(response: number): Promise<void| number>;
}

```
<img width="575" alt="Screenshot 2019-09-26 at 11 41 35" src="https://user-images.githubusercontent.com/16578374/65677953-cba46700-e052-11e9-8e3f-49c2ae11224e.png">

**Comment by erikrose** [comment]
It's likely because the underlying Sphinx constructs that our directives emit have only a "class" type: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html?highlight=javascript#the-javascript-domain. To get it to say "interface" instead, we'd have to punch down a level of abstraction.

**Comment by mdolgich** [comment]
Thank you I did not know that the Sphinx constructs does not include an interface type. Still really new in the usage of this tool. Thank you for your help.

**Comment by erikrose** [comment]
Only if you're planning to work on it. I'm probably not going to get to it myself.
