### ISSUE TITLE
js:mod role does not add 'module-' prefix to href

### ISSUE THREAD

**Issue by MarcelloPerathoner** [mozilla/sphinx-js#127]
Referencing with the js:mod role does not work because the link href lacks the 'module-' prefix that is customary for modules.

**Comment by erikrose** [comment]
Are you referring to the js:module directive, https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-js:module ? I’m hoping not, since sphinx-js doesn’t do anything at all to or with it.

**Comment by erikrose** [comment]
Please comment and clarify if you want to keep this issue alive. Thanks!
