### ISSUE TITLE
Class node without children raises NoneType Exception

### ISSUE THREAD

**Issue by nicolaiwolko** [mozilla/sphinx-js#131]
Hi everybody,

#### I encountered the following exception in my typescript project:

> Exception occurred:
  File "[...]/venv/lib/python3.7/site-packages/sphinx_js/typedoc.py", line 292, in convert_node
    for child in node.get('children'):
TypeError: 'NoneType' object is not iterable

#### Following fix worked for me:

Applying a default empty list at the node children get function:
https://github.com/mozilla/sphinx-js/blob/master/sphinx_js/typedoc.py#L292

**Before:**
`for child in node.get('children'):`
**After:**
`for child in node.get('children', []):`

**Comment by erikrose** [comment]
Thanks for the report!
