### ISSUE TITLE
How to document entire module

### ISSUE THREAD

**Issue by munawarb** [mozilla/sphinx-js#138]
I have a module like this:
```javascript
module.exports = exports = {
    /**
    ...
    **/
    someFunction: (...args) => {...},
    ...
};
```
In my index file I'm explicitly writing directives like `.. autofunction:: someFunction`. Is there a way to have SphinxJS automatically iterate over my module and build the documentation instead of me writing a directive for each function? I've looked at the module directive but am confused by it. Is there any way to achieve this like we can with `autoclass`? Or do I have to convert my module into a class to get this functionality with auto-iterating over members?

**Comment by erikrose** [comment]
It's a great idea! There's no `automodule` directive yet, but it shouldn't be too hard to add one. See #5.
