### ISSUE TITLE
Need an example.

### ISSUE THREAD

**Issue by 625781186** [mozilla/sphinx-js#139]
Can you provide a minimal example of auto-generated documentation? 
I honestly don't understand the steps in README.
Thank you.

**Comment by 625781186** [comment]
I don't understand the problem as this [link](https://stackoverflow.com/questions/51300744/sphinx-js-doesnt-generate-documentation-from-js-files) .

So does sphinx-js still require `a human to manually` extract all the functions and write them to RST?

**Comment by erikrose** [comment]
You can manually name the functions using autofunction, or you can use autoclass to automatically pull in all the methods of the class. See https://mozilla.github.io/fathom/utilities.html#NiceSet for an example, and compare the source of the page, at https://mozilla.github.io/fathom/_sources/utilities.rst.txt. Someday we will also have an automodule directive, which will loop through a whole module and dump the contained classes and functions. sphinx-js—and Sphinx in general—really shows its strength when your autogenerated docs are embedded in sections of handwritten prose.
