### ISSUE TITLE
No recursion

### ISSUE THREAD

**Issue by Notmarrco** [mozilla/sphinx-js#140]
Hi,

I was trying to use sphinx-js but I always got the `No JSDoc documentation was found for object xxx or any path ending with that.`

In the end, I saw that the SuffixTree wasn't filled correctly. It seems to me that there is no recursion.

I modified `doclets.py` to add `comment.add('-r')` in analyze jsdoc and then it worked...

Was I missing something ?

**Comment by erikrose** [comment]
Please use the ``jsdoc_config_path`` config option to point to a custom JSDoc config file that turns on recursion. I considered turning it on by default, but sometimes that makes things worse: for instance, when there's a node_modules folder around. Imagine recursing through 2000 installed packages! :-)

**Comment by erikrose** [comment]
I just noticed #16, which lays out a reasonable design for doing recursion by default. So keep hope for the long run, and remember that patches are welcome. :-)
