### ISSUE TITLE
Enable the '.' character in names paths when parsing them?

### ISSUE THREAD

**Issue by ecsecta** [mozilla/sphinx-js#143]
Hi,
as a first time user of sphinx-js I ran across an error when trying to use it with Typescript code.
Typescript version: 3.9.3
Typedoc version: 0.17.7

The error is like this:
`parsimonious.exceptions.ParseError: Rule 'path' didn't match at '../../docs/abstractS'`

The error is triggerd by this path input value, which seems to hold an '.' character in the name:
`../../docs/abstractSigner.module:abstractSigner`

Allowing the '.' character in names in the parsers grammar in 'sphinx_js/parsers.py', seems to solve the issue:
`name = ~r"(?:[^(/#~\\]|\\.)+"`
instead of
`name = ~r"(?:[^(/#~.\\]|\\.)+"`

Is it possible to change the rule for names like this without raising new problems? I would add a Pull Request then.

TIA

**Comment by skddc** [comment]
I ran into the same issue, and this change seems to fix it.

**Comment by erikrose** [comment]
Should be fixed in 63ec39950798140490815c348e5d25bfc4f265de.

**Comment by ecsecta** [comment]
Great, Thank you very much :-)
