### ISSUE TITLE
cannot generate ts docs

### ISSUE THREAD

**Issue by tabVersion** [mozilla/sphinx-js#155]
Appreciate your great work.
But I encountered some problems when trying to generate doc for ts files. I tried the test file at `sphinx-js/tests/test_build_ts/source`.
To reproduce:
1. `mv docs _docs`
2. `sphinx quickstart` and all settings are kept as default ones
3. copy all file all `.rst` files and conf.py from `_docs` to `docs`
4. `make html` at dir `docs`

Then I got the following error:

```bash
Running Sphinx v1.8.3

Using TypeScript 4.0.3 from /tmp/quzha/nni-node-linux-x64/lib/node_modules/typescript/lib

JSON written to /tmp/tmp0zxh807n

building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 16%] autoclass_star
reading sources... [ 33%] autoclass_constructorless
reading sources... [ 50%] autoclass_class_with_interface_and_supers
/home/quzha/v-bzhang/anaconda/lib/python3.7/site-packages/sphinx/util/nodes.py:94: FutureWarning:
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
reading sources... [ 66%] autoclass_exported
reading sources... [ 83%] index

Sphinx error:
No JSDoc documentation was found for object "class.ClassDefinition" or any path ending with that.
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 2
```

I don't know why sphinx-js still use jsdoc even if `js_language='typescript'`.

**Comment by tabVersion** [comment]
Node v10.22.1
TypeDoc 0.19.2
sphinx-js 3.0.1

**Comment by skddc** [comment]
You need to try sphinx-js 3.1.

**Comment by erikrose** [comment]
Yes, please try 3.1 and make sure that doesn't solve your problem. It's a major rewrite, it brings TypeScript support to non-experimental stratus, and it's reported working with real-world TypeScript projects.

**Comment by tabVersion** [comment]
Thanks for supporting me. Upgrading sphinx-js solves my problem.

**Comment by erikrose** [comment]
Glad to hear it! You're welcome! (And thanks, @skddc!)
