### ISSUE TITLE
Support for project-local typedoc or jsdoc?

### ISSUE THREAD

**Issue by bchopson** [mozilla/sphinx-js#157]
Is there a way to use a project-local version of typedoc or jsdoc installed to `node_modules`? If not, would it be possible to use npx, instead of modifying one's PATH?

**Comment by erikrose** [comment]
What difficulty are you having modifying PATH? If there's a common problem, we could add a pref for the full path to the tools.

**Comment by bchopson** [comment]
Modifying my PATH is easy enough, however it would be nice to not have that as a project setup step for subsequent developers. Instead of saying "be sure to modify your path so you can build the docs" in my project's README, it would be preferable to specify the path to typedoc in the config, so that once they have installed node and python dependencies, they will be set to build the docs.

**Comment by erikrose** [comment]
Ah, I assumed you'd have a makefile or something similar where you could set the path once and for all. Are you having developers run `sphinx-build` manually? If not, Sphinx's own makefile would be a place you could add `PATH=...`.

Regardless, I'd take a PR to add a `typedoc_path` config option. The operand should be conf.py-relative to match the rest of the options that take relative paths.

**Comment by bchopson** [comment]
Modifying the path in the makefile should work fine for me. Feel free to close.

**Comment by erikrose** [comment]
Thanks!
