### ISSUE TITLE
ERROR: sphinx 3.5.4 has requirement docutils<0.17,>=0.12, but you'll have docutils 0.17 which is incompatible.

### ISSUE THREAD

**Issue by colin-guyon** [mozilla/sphinx-js#172]
Hi, this is what I get when doing a `pip install sphinx-js` (on Ubuntu 20.10, with either Python 3.7 or 3.8.6).
Is there something to update on your side to be able to install sphinx-js ?
Thanks

**Comment by erikrose** [comment]
I see it too. I'll update the dependency declaration. Thanks!

**Comment by erikrose** [comment]
So, Sphinx must have changed its own dependency declaration about `docutils`. sphinx-js says "give me any old version of docutils", but Sphinx insists on a version <0.17. pip should be able to resolve that set of constraints but doesn't yet by default. In the short term, pass `--use-feature=2020-resolver` to pip, and it'll work for you. In the meantime, I'll have to decide what makes the most sense on my end. I'll probably just drop our declared dependency on docutils, even though we use it directly.

**Comment by erikrose** [comment]
I'd cut a release, but CI is failing due to somebody's docker server error. In the meantime, feel free to pull from master, or use the workaround. Thanks for taking the time to report this!

**Comment by erikrose** [comment]
There we go. Passing now.

**Comment by erikrose** [comment]
3.1.2 is up! https://pypi.org/project/sphinx-js/3.1.2/

**Comment by colin-guyon** [comment]
Oh great, thanks for your reactivity ! :)

**Comment by erikrose** [comment]
My pleasure! :-D
