### ISSUE TITLE
Some clarification needed in README

### ISSUE THREAD

**Issue by wolfiex** [mozilla/sphinx-js#185]
"write a folder full of reStructuredText files"
Is a slightly confusing command unless you are already familiar with sphinx and do not use apidoc.

An anyone give a working example of these files.

**Comment by Gallaecio** [comment]
A single, empty `index.rst` file does the trick. To expand on that, i.e. add actual content to the file, you can follow the Sphinx documentation.

**Comment by willkg** [comment]
Thank you!
