### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by henryborchers** [mozilla/sphinx-js#188]
I don't see any attention in this repo. There has been no updates in almost a year compared with the regular updates it was getting. On top of that, the Jinja requirement is pined to less than 3. (It looked like there was an PR for updating requirements to Jinja >3.0 but it seemed like the author eventually pulled it.)

**Comment by willkg** [comment]
It's in my queue to triage issues and PRs in this project. It's in a maintenance slumber at the moment.

If that's not good enough for you (which is fine), I encourage you to find an alternative and go with that.
