### ISSUE TITLE
3.1.2: missing git tag

### ISSUE THREAD

**Issue by kloczek** [mozilla/sphinx-js#196]
According to https://pypi.org/project/sphinx-js/ latest version is 3.1.2 howeve here there is no coresponding git tag.

**Comment by willkg** [comment]
I can verify this tomorrow, but I think it's this commit: https://github.com/mozilla/sphinx-js/commit/91d35b81cff76dc2e3f35558dbb66c1999c17690

If so, I can create a tag for that later this week.

**Comment by kloczek** [comment]
Thank you 😃

**Comment by willkg** [comment]
I compared file sizes and I'm 98% sure that 3.1.2 is based on that commit, so I created the tag and pushed it.

@lonnen ^^^ Let me know if you want me to undo that or want something different.

**Comment by kloczek** [comment]
gentle ping .. 😃

**Comment by willkg** [comment]
Whoops--I pushed the tag to the wrong remote. Sorry about that! Thank you for catching it!
