### ISSUE TITLE
Could not import extension sphinx_js

### ISSUE THREAD

**Issue by salarmzn** [mozilla/sphinx-js#202]
I have installed sphinx-js but I have a problem when I tried adding the sphinx_js extensions on the conf.py file. The error is mentioned below in building the HTML. I will be happy if you guide me in this regard.

 Could not import extension sphinx_js (exception: cannot import name 'Mapping' from 'collections' (C:\Python310\lib\collections\__init__.py))

**Comment by willkg** [comment]
This is covered in issue #186. There's work being done on it, but it's been slow.
