### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by diogobaltazar** [mozilla/sphinx-js#203]
# Issue

Can't build the documentation with sphinx when installing the module ``sphinx-js==3.1.2``.

# Reproduce

```sh
(.env) python
>>> import sphinx_js
...
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (.env/lib/python3.8/site-packages/markupsafe/__init__.py)
```

# Hints

Version ``sphinx-js==3.1.2`` has a dependency on ``markupsafe==2.0.1`` which has removed ``soft_unicode`` (see [Version 2.1.0](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) release notes).

# Resolved

Resolved by reverting the version to ``2.0.1`` with ``pip install markupsafe==2.0.1``

**Comment by willkg** [comment]
This was fixed in abb38d2e.
