### ISSUE TITLE
transfer sphinx-js project

### ISSUE THREAD

**Issue by willkg** [mozilla/sphinx-js#233]
Issue #226 caused us to sit down and figure out the future of this project. @hoodmane is maintaining a fork for pyodide. We worked out that we're going to transfer this project to @hoodmane. 

This covers the tasks to transfer:

* [x] remove `CODE_OF_CONDUCT.md`
* [x] go through and remove Mozilla branding--this will no longer be a Mozilla-owned project
* [x] remove author names where appropriate with a TODO to fill new ones in
* [ ] transfer project to new owner
* [ ] update permissions
* [ ] update pypi permissions

**Comment by hoodmane** [comment]
> remove CODE_OF_CONDUCT.md

Seems like a fine code of conduct but I guess it is very Mozilla branded. I guess we can copy our own version from here:
https://github.com/pyodide/pyodide/blob/main/CODE-OF-CONDUCT.md

>  remove author names where appropriate

I'm always confused about what the etiquette is with this for forks and ownership transfers. I think that the original authors are still authors but no longer maintainers. The primary argument for removing old people is if they want to be removed for some reason or if they are getting contacted by people about it? What do you think?

cc @rth @ryanking13 @erikrose

Thanks again @willkg for your work on this project!

**Comment by willkg** [comment]
In other projects, I have a contributors file where people who've contributed are listed. This project doesn't do that, but it could. We could seed it with the git committers.

I find "authors" and "maintainers" project metadata which gets tracked in various places to be an invitation for users to contact when they need help. Thus, people who aren't active on a project shouldn't be listed there.

I'm not aware of any virtues to being listed in "authors" or "maintainers" but not being active.

**Comment by hoodmane** [comment]
The only reason I'm sensitive of this point is that I observed an argument about this point in the past: a new maintainer removed the previous maintainer from the authors list and the old maintainer got angry. 

> "authors" and "maintainers" project metadata which gets tracked in various places to be an invitation for users to contact when they need help. Thus, people who aren't active on a project shouldn't be listed there.

This seems like a good argument.

**Comment by willkg** [comment]
I respect the work Erik put into sphinx-js and you're right--we shouldn't just drop things like that entirely. I added a CONTRIBUTORS file like [I have with Bleach](https://github.com/mozilla/bleach/blob/main/CONTRIBUTORS) in PR #234. Does that look ok?

**Comment by hoodmane** [comment]
Looks great.

**Comment by rth** [comment]
> Seems like a fine code of conduct but I guess it is very Mozilla branded. I guess we can copy our own version from here:
[pyodide/pyodide@main/CODE-OF-CONDUCT.md](https://github.com/pyodide/pyodide/blob/main/CODE-OF-CONDUCT.md?rgh-link-date=2023-09-28T18%3A16%3A57Z)

Ours is probably also a bit Mozilla branded, as we didn't change it from the time when Pyodide was a Mozilla project :)

**Comment by hoodmane** [comment]
At least Pyodide's COC doesn't tell you to email Mozilla to report violations though...

**Comment by erikrose** [comment]
Thanks for taking on the mantle, @hoodmane! I'm fine being listed as `author`, as I've never got direct mails from anyone on any other of my projects emeritus. However, I've always encouraged maintainers down the line to stick themselves in there instead. All I would request is I'm listed in the readme as originating the project so I don't seem like a liar when I cite it in my resume etc. Thanks again for taking over! :-D

**Comment by willkg** [comment]
I added a Provenance section to the README about where sphinx-js originated and also pointing to the CONTRIBUTORS file for details. I think that covers things.

**Comment by erikrose** [comment]
Beautiful. Much appreciated! :-D

**Comment by willkg** [comment]
I wrote up a bug to transfer the project from `mozilla` to `pyodide`. I'm not sure how long it'll take, but I'll keep tabs on it.

**Comment by raucao** [comment]
Is something still blocking the repo from being transferred? The tasks seem to have been completed, and only the actual transfer seems to be left to do.

**Comment by willkg** [comment]
I haven't heard any updates in many many weeks. I don't want to keep sitting on this, so I'm changing gears and I'm going to deprecate the project.

I'll close this out in favor of #247 . Sorry!

**Comment by hoodmane** [comment]
It's unfortunate that the Open Source Collective doesn't seem able to sign legal agreements. Thanks for trying though @willkg. I suppose if we want we can perfectly well publish under `sphinx-js-2` or `sphinx-js-maintained` or some other name.
