### ISSUE TITLE
autoclass directive cuts off module name when used with a typescript interface

### ISSUE THREAD

**Issue by Towerism** [mozilla/sphinx-js#73]
It renders: "interface, exported from odule_her", but it should say "interface, exported from module_here". The first and last letter are cut off from the module name. A quick glance at the code tells me the line referenced below is the culprit. It seems oddly specific to leave off the first and letter, doesn't it? I would guess that earlier versions of typedoc would display quotes around the module name; however, it seems incorrect when the latest version of typedoc is used, as the module name gets cut off.

https://github.com/erikrose/sphinx-js/blob/cb249103ed394f670cd316ce0e9e31424cb3a341/sphinx_js/typedoc.py#L257

**Comment by erikrose** [comment]
@WimYedema Any ideas?

**Comment by WimYedema** [comment]
Indeed, when I look at a typedoc json file I tested this on I see this:

`                        "name": "\"class\"",
                        "kind": 1,
                        "kindString": "External module",
`

We could test for the presence of quotes and remove them if they're there...

**Comment by Towerism** [comment]
I was thinking that was the issue. If you guys could use the extra capacity, I can submit a pull request with this change.

**Comment by erikrose** [comment]
We're always open to more capacity. :-) My only concern here is whether this approach will be a reliable one. It sounds like sometimes there are quotes and sometimes there aren't. It is *possible* for an attr name to start with a quote, e.g.

```js
{'"foo"': 'weird attr name'}
```

If we can figure out a reliable approach, that'd be preferable. But we've been forced to guess by jsdoc before, so guessing right most of the time is better than acting wrong.

**Comment by Towerism** [comment]
Is cleansing the name really desirable then? Maybe it would be better to just "do whatever the typedoc/jsdoc" in this case.

**Comment by erikrose** [comment]
I generally try to stick to the other tools’ behavior if I can’t do something clearly better. That way, a codebase isn’t coupled to any tool. Want to take a look and see what typedoc generates on its own?

**Comment by erikrose** [comment]
What I meant was "What does the formatted (HTML) documentation that typedoc emits look like?" Are they also having spurious quotes?

**Comment by Towerism** [comment]
Oh no, no spurious quotes in the formatted document emitted by typedoc; that plus the JSON being free of spurious quotes leads me to believe it's a version difference.

**Comment by erikrose** [comment]
Sounds like stripping a single surrounding pair of " or ' is the best approach.

**Comment by erikrose** [comment]
I got rid of the "exported from" link in the big TS rewrite of #120. Does anybody miss it? If so, most of the hard work toward showing it is already in there. Please open a ticket for that if so.
