### ISSUE TITLE
typedoc order of class methods with autoclass?

### ISSUE THREAD

**Issue by graup** [mozilla/sphinx-js#82]
When using autoclass in javascript mode, the constructor documentation always appears at the top of the class. This is messed up in typescript mode.

It seems that all class instance methods are ordered alphabetically, and in typescript mode the constructor ends up being a method called "new Class()" which is sorted under N (and not at the top as it used to be in normal js mode). 

I created a failing test case showing the problem: https://github.com/erikrose/sphinx-js/pull/81

**Comment by WimYedema** [comment]
I appreciate the report. A very necessary first step in improving typescript support. I'm currently not able to fix this myself, but like erik, I'd be happy to review a fix.

**Comment by graup** [comment]
#92 looks like a good fix (still have to test it).

About properties appearing mixed together with methods, I think it's just a renderer issue. typedoc.py generates the list in the correct order, but it is sorted by `name` [in the renderer](https://github.com/mozilla/sphinx-js/blob/master/sphinx_js/renderers.py#L273-L305). Maybe we could fix this by sorting by `longname` instead?

The typedoc.py output looks something like this:
`
[
{
  "name": "new Accounts",
  "longname": "external:accounts/index~Accounts~new Accounts"
},
{
  "name": "client",
  "longname": "external:accounts/index~Accounts#client",
},
{
  "name": "create",
  "longname": "external:accounts/index~Accounts.create",
},
]
```

Longname includes `#` and `~` so properties will be sorted separately from methods.
