### ISSUE TITLE
"ValueError: No JSON object could be decoded" if libraries cannot be loaded

### ISSUE THREAD

**Issue by whimboo** [mozilla/sphinx-js#83]
When running jsdoc with a dependent library not being available shows a ValueError instead of a user friendly message to diagnose the problem. I was upgrading brew packages while trying to run sphinx_js in parallel, and got the following failure:

> Exception occurred:
>   File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> The full traceback has been saved in /var/folders/4k/sf4gz5fn3kl9hr3nd7pzbvhc0000gn/T/sphinx-err-SfpWpO.log, if you want to report the issue to the developers.

[sphinx-err-SfpWpO.log](https://github.com/mozilla/sphinx-js/files/2643229/sphinx-err-SfpWpO.log)

Checking that log file and updating `jsdoc.py` to print out the current jsdoc command lead me to:

> % jsdoc
> dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
>   Referenced from: /usr/local/bin/node
>   Reason: image not found

Reason is that this library is about to get updated or was updated. As such jsdoc couldn't load it and failed with this non-helpful failure message.

Not sure where this jsdoc.py actually comes from because I don't see it in this repository, but I get this version of sphinx_js by running `mach doc` on `mozilla-central`.

**Comment by erikrose** [comment]
Hi, and thanks for the report! jsdoc.py is basically what doclets.py was called in an earlier version of sphinx-js.

This uninformative message should be fixed now. Now we catch the ValueError and say…

> jsdoc found no JS files in the directories [foo, bar, baz]. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.
